# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f443da735621501c15dec86d81a885d39ca58e7d43ce918805846a95883f479ee943dc0e5d9c678af511e5819dfa027673ab17821791626cc568d7412cae71

test:
  secret_key_base: e0a4f44326c663fbbc6132310f11ff7500c94bf418982e3c6f03b3f9ed8cc6c4b1ed58b073ee5dd781c6cf01420fc28b990e85839d132758b9815043e2569905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
